version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --workers 1
    environment:
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: performance
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
*** End Patch